name: tsuyomi

services:
  tsuyomi:
    image: ghcr.io/suwayomi/suwayomi-server:v2.1.1867
    container_name: tsuyomi
    restart: unless-stopped

    ports:
      - "${PORT:-4567}:4567"

    volumes:
      - type: bind
        source: ${MANGA_DOWNLOADS:?Set MANGA_DOWNLOADS in the environment file}
        target: /home/suwayomi/.local/share/Tachidesk/downloads
      - type: bind
        source: ${CONTAINERS_DATA:?Set CONTAINERS_DATA in the environment file}/tsuyomi-files
        target: /home/suwayomi/.local/share/Tachidesk

    environment:
      TZ: ${TZ:-America/Toronto}
      FLARESOLVERR_ENABLED: "true"
      FLARESOLVERR_URL: http://flaresolverr:8191
      DOWNLOAD_AS_CBZ: "true"
      EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'

    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/thephaseless/byparr:3.0.4
    container_name: flaresolverr
    restart: unless-stopped
    init: true

    environment:
      TZ: ${TZ:-America/Toronto}
