services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped

    ports:
      - "13378:80"

    volumes:
      - ${CONTAINERS_DATA}/audiobookshelf/config:/config
      - ${CONTAINERS_DATA}/audiobookshelf/metadata:/metadata
      - ${MEDIA_ROOT}/audiobooks:/audiobooks:ro
      - ${MEDIA_ROOT}/podcasts:/podcasts:ro

    environment:
      TZ: ${TZ:-America/Toronto}
