services:
  filebrowser:
    image: gtstef/filebrowser:stable
    user: filebrowser
    volumes:
      - /mnt/media:/media 
      - /mnt/photos-videos:/photos-videos
      - /mnt/photos-videos-test:/photos-videos-test
      - /mnt/containers-data:/containers-data
      - ./config.yaml:/home/filebrowser/config.yaml:ro
    ports:
      - 8010:80
    restart: unless-stopped
