---
state: present
restic_dir: /home/ubuntu/resticprofile
RESTIC_PHOTOS_PASSPHRASE: "{{ lookup('env', 'RESTIC_PHOTOS_PASSPHRASE') }}"
RESTIC_VIDEOS_PASSPHRASE: "{{ lookup('env', 'RESTIC_VIDEOS_PASSPHRASE') }}"
HETZNER_SFTP_USER: "{{ lookup('env', 'HETZNER_SFTP_USER') }}"
HETZNER_SFTP_HOST: "{{ lookup('env', 'HETZNER_SFTP_HOST') }}"
HEALTHCHECKS_PHOTOS_HETZNER_URL: "{{ lookup('env', 'HEALTHCHECKS_PHOTOS_HETZNER_URL') }}"
HEALTHCHECKS_PHOTOS_ONEDRIVE_URL: "{{ lookup('env', 'HEALTHCHECKS_PHOTOS_ONEDRIVE_URL') }}"
HEALTHCHECKS_VIDEOS_HETZNER_URL: "{{ lookup('env', 'HEALTHCHECKS_VIDEOS_HETZNER_URL') }}"
HEALTHCHECKS_VIDEOS_ONEDRIVE_URL: "{{ lookup('env', 'HEALTHCHECKS_VIDEOS_ONEDRIVE_URL') }}"
RESTIC_JELLYFIN_PASSPHRASE: "{{ lookup('env', 'RESTIC_JELLYFIN_PASSPHRASE') }}"
HEALTHCHECKS_JELLYFIN_ONEDRIVE_URL: "{{ lookup('env', 'HEALTHCHECKS_JELLYFIN_ONEDRIVE_URL') }}"
JELLYFIN_API_KEY: "{{ lookup('env', 'JELLYFIN_API_KEY') }}"
