all:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.1.130
      ansible_user: ubuntu
    bahamut:
      ansible_host: 192.168.1.101
      ansible_user: root
  children:
    app_servers:
      hosts:
        ubuntu-01:
    file_servers:
      hosts:
        bahamut:
