all:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.1.130
      ansible_user: ubuntu
    ubuntu-02:
      ansible_host: 192.168.1.131
      ansible_user: ubuntu
    bahamut:
      ansible_host: 192.168.1.101
      ansible_user: root
    monitoring-01:
      ansible_host: 192.168.1.150
      ansible_user: ubuntu
  children:
    app_servers:
      hosts:
        ubuntu-01:
        ubuntu-02:
    file_servers:
      hosts:
        bahamut:
    monitoring_servers:
      hosts:
        monitoring-01:
