services:
  homepage-data:
    image: nginx:1.27.5-alpine
    container_name: homepage-data
    restart: unless-stopped

    volumes:
      - ${CONTAINERS_DATA}/static-data:/usr/share/nginx/html:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:v2.4.0
    container_name: homepage
    restart: unless-stopped

    ports:
      - "${PORT:-80}:3000"

    volumes:
      - homepage_config:/app/config

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: 1000
      PGID: 100
      TZ: ${TZ:-America/Toronto}

volumes:
  homepage_config:
