services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    ports:
      - "${PORT:-80}:3000"

    volumes:
      - homepage_config:/app/config

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: 1000
      PGID: 100
      TZ: ${TZ:-America/Toronto}

volumes:
  homepage_config:
