---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Home:
    - Containers:
        icon: mdi-home
        widget:
          type: customapi
          url: http://homepage-data/household-items.json
          refreshInterval: 60000
          display: dynamic-list
          mappings:
            items: items
            name: remote
            label: container_names

- Infrastructure:
    - Physical hosts:
        icon: mdi-server
        widget:
          type: customapi
          url: http://homepage-data/servers.json
          refreshInterval: 60000
          display: dynamic-list
          mappings:
            items: hosts
            name: name
            label: ip
    - bahamut VMs:
        icon: mdi-server-network
        widget:
          type: customapi
          url: http://homepage-data/servers.json
          refreshInterval: 60000
          display: dynamic-list
          mappings:
            items: hosts.0.vms
            name: name
            label: ip
    - eiko VMs:
        icon: mdi-server-network
        widget:
          type: customapi
          url: http://homepage-data/servers.json
          refreshInterval: 60000
          display: dynamic-list
          mappings:
            items: hosts.1.vms
            name: name
            label: ip
    - dev-01 SSH user:
        icon: mdi-account-key
        widget:
          type: customapi
          url: http://homepage-data/servers.json
          refreshInterval: 60000
          mappings:
            - field: hosts.1.vms.0.additional_info.ssh-user
              label: SSH user
