services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped

    ports:
      - "${PORT:-13378}:80"

    volumes:
      - type: bind
        source: ${CONTAINERS_DATA}/config
        target: /config
      - type: bind
        source: ${CONTAINERS_DATA}/metadata
        target: /metadata
      - type: bind
        source: ${AUDIOBOOKS_ROOT}
        target: /audiobooks
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${PODCASTS_ROOT}
        target: /podcasts
        read_only: true
        bind:
          create_host_path: false

    environment:
      TZ: ${TZ:-America/Toronto}
